# Generated by Django 2.2.1 on 2019-07-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
